# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ce48da2f39c1fa2ef729ff3eee7f3a4"
name = "test"
handle = "test-14252"
application_url = "https://ellis-forget-significant-cartoons.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nebula-etl-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ellis-forget-significant-cartoons.trycloudflare.com/auth/callback",
  "https://ellis-forget-significant-cartoons.trycloudflare.com/auth/shopify/callback",
  "https://ellis-forget-significant-cartoons.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
